spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console

  data:
    redis:
      cluster:
        nodes:
          - localhost:7000
          - localhost:7001
          - localhost:7002
      timeout: 6000


logging:
  level:
    org.springframework.data.redis: debug
